<a href="https://colab.research.google.com/github/varunkite/DragGANpvt/blob/main/Fake_Currency_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Taking the independent variables of features as variance, skewness, curtosis, entropy that depends upon class that are independent variables that depends on the class whether it shows it as 0 and 1

## Data preprocessing


In [ ]:
# importing required libraries
import numpy as np
import pandas as pd

In [ ]:
# loading data
dataset = pd.read_csv('/content/BankNoteAuthentication.csv')
#recruiting 5 datarows from the first column using .head() method
dataset.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [ ]:
#Recruiting 5 datarows from the last column using .tail() method
dataset.tail()

variance  skewness  curtosis  entropy  class
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

In [ ]:
#printing independent variables
X = dataset.iloc[:,:-1].values
print(X)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [ ]:
#printing dependent variables
y = dataset.iloc[:,-1].values
print(y)

[0 0 0 ... 1 1 1]


In [ ]:
#checking null values whether the null values are there in the dataset or not
null_values = dataset.isnull().sum()
print("Column with null values: ")
print(null_values[null_values > 0])

Column with null values: 
Series([], dtype: int64)


## Training the model

In [ ]:
#Splitting and training the data using train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

In [ ]:
print(X_train)

[[-1.2943    2.6735   -0.84085  -2.0323  ]
 [-0.40857   3.0977   -2.9607   -2.6892  ]
 [-1.5228   -6.4789    5.7568    0.87325 ]
 ...
 [ 0.6005    0.99945  -2.2126    0.097399]
 [ 2.0165   -0.25246   5.1707    1.0763  ]
 [-2.0759   10.8223    2.6439   -4.837   ]]


In [ ]:
print(X_test)

[[ -1.7713   -10.7665    10.2184    -1.0043  ]
 [  5.1321    -0.031048   0.32616    1.1151  ]
 [ -2.0149     3.6874    -1.9385    -3.8918  ]
 ...
 [ -2.1652     3.0211    -2.4132    -2.4241  ]
 [  0.48797    3.5674    -4.3882    -3.8116  ]
 [ -4.3667     6.0692     0.57208   -5.4668  ]]


In [ ]:
print(y_train)

[1 1 1 ... 1 0 0]


In [ ]:
print(y_test)

[1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 0
 1 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0
 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0
 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0
 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0
 1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0
 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 1
 1 0 0 0 1 0 0 1 1 0 1 1 0 1 1 1]


## Feature Scaling

In [ ]:
#Combining different data sets using and feature scaling to get the standard independent variables
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.60234962  0.13706318 -0.52441296 -0.41116219]
 [-0.291035    0.21026408 -1.02368742 -0.72585061]
 [-0.68266235 -1.4422953   1.02948859  0.98074362]
 ...
 [ 0.06363093 -0.15181461 -0.8474923   0.60907164]
 [ 0.5613238  -0.36784698  0.89144827  1.07801487]
 [-0.87706484  1.54323822  0.29632752 -1.75475574]]


In [ ]:
print(X_test)

[[-0.77000464 -2.18217308  2.08030018  0.08130195]
 [ 1.65638872 -0.32963963 -0.24955469  1.09660204]
 [-0.85562469  0.31202402 -0.78293531 -1.301957  ]
 ...
 [-0.90845183  0.19704581 -0.89473831 -0.59885426]
 [ 0.02407911  0.29131655 -1.3598972  -1.26353714]
 [-1.68223069  0.72303272 -0.19163475 -2.05646189]]


## Training the model

In [ ]:
#Training the model using logisticRegressing, Here the hyperparameters that are used in the model are liblinear and multi class is auto and random_state to get the different parameters work on the model
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='liblinear',random_state=42,multi_class='auto')
clf.fit(X_train,y_train)

LogisticRegression(random_state=42, solver='liblinear')

In [ ]:
#Getting accuracy and confusion_matrix using accuracy_score and confusion_matrix using metrics module. We got good accuracy score that is 99%
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_pred,y_test)
print('Confusion matrix:')
print(cm)
accuracy = accuracy_score(y_pred,y_test)
print(accuracy)

Confusion matrix:
[[154   0]
 [  3 118]]
0.9890909090909091


In [ ]:
#predicting the model whether the output is correct or not
y_pred = np.array(clf.predict(X_test))

In [ ]:
#Checking the data row 50 of the variance,skewness,curtosis,entropy and class
dataset.iloc[50]

variance    4.3239
skewness   -4.8835
curtosis    3.4356
entropy    -0.5776
class       0.0000
Name: 50, dtype: float64

In [ ]:
#predicting whether our model gives correct output or not
single_record = sc.transform(X[50].reshape(1,-1))
fake_note = clf.predict(single_record)
print(fake_note)

[0]
